# Generated by Django 2.1 on 2018-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
